In [1]:
import torch

In [2]:
print(torch.__version__)

2.0.1


In [3]:
###Introduction to Tensors
#These are the ways to represent data

In [80]:
##Creating Tensors

In [4]:
#scalar
scalar = torch.tensor(7)

In [5]:
scalar

tensor(7)

In [6]:
#scalar attributes has no dimensions
scalar.ndim

0

In [7]:
#Get tensor value
scalar.item()

7

In [8]:
#Vector
vector = torch.tensor([1,1])
vector

tensor([1, 1])

In [9]:
vector.ndim

1

In [10]:
#Vector
vector = torch.tensor([[1,1],[7,7]])
vector

tensor([[1, 1],
        [7, 7]])

In [11]:
vector.ndim

2

In [12]:
#Shape of a matrix
vector.shape

torch.Size([2, 2])

In [13]:
#Matrix
MATRIX = torch.tensor([[1,1],
                       [9,10]])
MATRIX

tensor([[ 1,  1],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3,],[3,6,9],[2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [20]:
##Random Tensors
Random Tensors are important because the way many neural networks learn is that 
they start with tensors full of random numbvers and then adjust 
random numbers to better represent the data

SyntaxError: invalid syntax (2961472291.py, line 2)

In [21]:
###Creating a Random tensor of size (3,4)
random_tensor = torch.rand(3,4)

In [22]:
random_tensor

tensor([[0.9063, 0.8248, 0.7326, 0.0247],
        [0.2363, 0.7966, 0.8700, 0.7313],
        [0.6876, 0.9282, 0.2086, 0.5790]])

In [23]:
random_tensor.ndim

2

In [24]:
random_tensor.shape

torch.Size([3, 4])

In [25]:
random_tensor = torch.rand(10,3,4)

In [26]:
random_tensor

tensor([[[0.0482, 0.8461, 0.9065, 0.7975],
         [0.5905, 0.4757, 0.5083, 0.0066],
         [0.8402, 0.4390, 0.7781, 0.9881]],

        [[0.8451, 0.9106, 0.4815, 0.8920],
         [0.1637, 0.8710, 0.6632, 0.3354],
         [0.5111, 0.6070, 0.4823, 0.9709]],

        [[0.0290, 0.2991, 0.0459, 0.1423],
         [0.4835, 0.8646, 0.9167, 0.4984],
         [0.3553, 0.3081, 0.6591, 0.2996]],

        [[0.4994, 0.7420, 0.7081, 0.3272],
         [0.4996, 0.9261, 0.1669, 0.5282],
         [0.9630, 0.0457, 0.1388, 0.3251]],

        [[0.8549, 0.3976, 0.0516, 0.0976],
         [0.8523, 0.9672, 0.6805, 0.9804],
         [0.2754, 0.9513, 0.6408, 0.1230]],

        [[0.2920, 0.5834, 0.3321, 0.5128],
         [0.0640, 0.5304, 0.2171, 0.1378],
         [0.2665, 0.9712, 0.5564, 0.1474]],

        [[0.9144, 0.7837, 0.9734, 0.4233],
         [0.3813, 0.8681, 0.4661, 0.5977],
         [0.7822, 0.2060, 0.1085, 0.1875]],

        [[0.4482, 0.2948, 0.2998, 0.0561],
         [0.6080, 0.2972, 0.6882, 0.8944

In [27]:
random_tensor.ndim

3

In [28]:
#Create a random tensor with similar shape to an
#image tensor

In [29]:
random_image_tensor = torch.rand(224,224,3)

In [30]:
random_image_tensor 

tensor([[[0.3389, 0.4274, 0.8111],
         [0.2484, 0.3891, 0.4684],
         [0.5202, 0.5256, 0.7940],
         ...,
         [0.3844, 0.7098, 0.6483],
         [0.9977, 0.4102, 0.6745],
         [0.2396, 0.3574, 0.6224]],

        [[0.5985, 0.1967, 0.3875],
         [0.6516, 0.1456, 0.2008],
         [0.4601, 0.2983, 0.6274],
         ...,
         [0.9513, 0.2429, 0.6293],
         [0.0557, 0.8067, 0.5532],
         [0.4593, 0.1697, 0.8571]],

        [[0.0757, 0.1158, 0.0310],
         [0.8422, 0.4137, 0.5285],
         [0.4638, 0.1902, 0.3324],
         ...,
         [0.5515, 0.7753, 0.9345],
         [0.7056, 0.6469, 0.6887],
         [0.5908, 0.2275, 0.6101]],

        ...,

        [[0.7201, 0.1804, 0.9325],
         [0.8459, 0.2801, 0.6191],
         [0.8738, 0.3270, 0.8356],
         ...,
         [0.3917, 0.9499, 0.2172],
         [0.8895, 0.4781, 0.6266],
         [0.2291, 0.2864, 0.6297]],

        [[0.4096, 0.5598, 0.0765],
         [0.9062, 0.2451, 0.4227],
         [0.

In [31]:
random_image_tensor.ndim

3

In [32]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [33]:
#Example:
random_image_tensor_1 = torch.rand(3,224,224)
random_image_tensor_1.ndim, random_image_tensor_1.shape

(3, torch.Size([3, 224, 224]))

In [34]:
###Creation a tensor of all zeroes
###Used at masking
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
##Tensor Datatype
ones.dtype

torch.float32

In [37]:
###Creating a Range of Tensors

In [38]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
one_to_ten=torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [40]:
##Creating Tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)

In [41]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
###Tensor Data type
##dtype is about the data type
###device like cpu or gpu or cude (device="cuda")
###To track the gradient
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None,
                              device=None,
                              requires_grad=False)

In [43]:
float_32_tensor

tensor([3., 6., 9.])

In [44]:
##Tensor Operations
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)


In [45]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [46]:
##Creating a Tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2236, 0.0768, 0.8876, 0.3066],
        [0.7093, 0.5504, 0.4202, 0.3857],
        [0.8403, 0.4714, 0.4972, 0.7061]])

In [47]:
print(f"The size is: {some_tensor.shape}")
print(f"the tensor is: {some_tensor.shape}")
print(f"The tensor device: {some_tensor.device}")

The size is: torch.Size([3, 4])
the tensor is: torch.Size([3, 4])
The tensor device: cpu


In [48]:
##Tensor Operations like Addition, multiplication and Division
tensor = torch.tensor([3,4])

In [49]:
torch.mul(tensor, 4)

tensor([12, 16])

In [50]:
torch.add(tensor, 4)

tensor([7, 8])

In [51]:
torch.sub(tensor, 4)

tensor([-1,  0])

In [52]:
##Matrix Multiplication
##1. Element Wise Multiplication
##2. Matrix Multiplication (Dot Product)

In [53]:
tensor = torch.tensor([1,2,3])
print(tensor, "*", tensor)
print(tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [54]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 320 µs, sys: 115 µs, total: 435 µs
Wall time: 294 µs


tensor(14)

In [55]:
##mean, max, min
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [57]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [60]:
##There are issues with data types have a look
torch.mean(x.type(torch.float32))

tensor(45.)

In [61]:
torch.sum(x)

tensor(450)

In [62]:
##Find the position in tensor that has the minimum value
x.argmin()

tensor(0)

In [63]:
x[0]

tensor(0)

In [64]:
##Find the position to find the maximum value oin the tensor
x.argmax()

tensor(9)

In [65]:
x[9]

tensor(90)

In [66]:
#Reshaping, Viewing and stacking
#Squeeze in Tensorflow - Removes all '1' dimensions froma tensor
#Unsqueeze - Add a '1' dimension to a target tensor
#Permute -  Return a view of the input with dimensions permuted


In [67]:
x = torch.arange(1.,10,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [68]:
x.ndim

1

In [69]:
x.shape

torch.Size([9])

In [70]:
#Use Reshaped
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
#Change the View
z = x.view(1,9)
z.shape

torch.Size([1, 9])

In [72]:
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [73]:
#Changing z changes x (because a view of a tensor share the same 
#memory as the original tensor)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [74]:
#Stack tensors
x_stacked =torch.stack([x,x,x,x])

In [75]:
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [77]:
x_stacked.shape

torch.Size([4, 9])

In [78]:
#Practise
tensor_example = torch.rand(3,224,224)

In [79]:
tensor_example

tensor([[[0.5133, 0.9434, 0.8011,  ..., 0.2107, 0.2525, 0.9600],
         [0.2941, 0.0382, 0.8564,  ..., 0.0259, 0.1054, 0.4983],
         [0.9693, 0.9313, 0.6872,  ..., 0.4580, 0.0985, 0.0490],
         ...,
         [0.8072, 0.2926, 0.8404,  ..., 0.8619, 0.4872, 0.6790],
         [0.3826, 0.6594, 0.8574,  ..., 0.7836, 0.1797, 0.1635],
         [0.6971, 0.3613, 0.6483,  ..., 0.3519, 0.0650, 0.1236]],

        [[0.6766, 0.6241, 0.2022,  ..., 0.8292, 0.2776, 0.3623],
         [0.2039, 0.9925, 0.7799,  ..., 0.8845, 0.4137, 0.0503],
         [0.5910, 0.3087, 0.5411,  ..., 0.4249, 0.1952, 0.5153],
         ...,
         [0.0014, 0.0341, 0.3777,  ..., 0.9071, 0.9048, 0.4730],
         [0.3156, 0.9347, 0.3494,  ..., 0.5360, 0.0975, 0.2222],
         [0.7807, 0.0882, 0.9814,  ..., 0.8428, 0.7918, 0.7118]],

        [[0.9015, 0.1595, 0.3862,  ..., 0.4999, 0.9316, 0.0670],
         [0.9887, 0.8035, 0.8513,  ..., 0.8294, 0.3684, 0.8259],
         [0.4086, 0.8513, 0.7783,  ..., 0.0761, 0.9835, 0.